#!/bin/sh /etc/rc.common
# vpnhub: runs the OpenVPN client (started and stopped by /usr/bin/vpnhub, never enabled at boot)
USE_PROCD=1
start_service() {
	[ -f /var/run/vpnhub/openvpn.conf ] || return 0
	procd_open_instance
	procd_set_param command /usr/sbin/openvpn --config /var/run/vpnhub/openvpn.conf
	procd_set_param respawn 60 10 5
	procd_set_param stderr 1
	procd_close_instance
}
